// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EgressLogEntryDto = { id: string, provider: string, model: string, token_count: bigint, source_count: number, success: boolean, created_at: number, };
