// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteDto = {
  id: string;
  title: string;
  /**
   * Canonical ProseMirror-JSON body.
   */
  body: string;
  /**
   * Plain-text projection of `body` for snippets and display.
   */
  body_text: string;
  created_at: number;
  updated_at: number;
  deleted_at: number | null;
};
